### ISSUE TITLE
A table was not found

### ISSUE THREAD

**Issue by swasen** [singhateh/Laravel-Library-Management-system#1]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DATABASE.sessions' doesn't exist (SQL: select * from `sessions` where `id` = asNpGGLDoWrdiGq0HRiwISbmraUuIpx9oORQog5y limit 1)

**Comment by swasen** [comment]
php artisan session:table
php artisan migrate

solved

**Comment by singhateh** [comment]
Okay did you already solve the problem?
